---
title: "Exercise2 MAD"
output: html_document
---

```{r include=TRUE}
X <- read.table(text="
                math  scie  fran  lati  d-m
      jean      6.0   6.0   5.0   5.5   8.0
      aline     8.0   8.0   8.0   8.0   9.0
      annie     6.0   7.0   11.0  9.5   11.0
      monique   14.5  14.5  15.5  15.0  8.0
      didier    14.0  14.0  12.0  12.5  10.0
      andre     11.0  10.0  5.5   7.0   13.0
      pierre    5.5   7.0   14.0  11.5  10.0
      brigitte  13.0  12.5  8.5   9.5   12.0
      evelyne   9.0   9.5   12.5  12.0  18.0
      ")
```
#????????????????????????????????????
```{r include=TRUE}
#?????????????????????prcomp
res.pca <- prcomp(X)
res.pca
str(res.pca)
#?????????????????????????????????,???????????????????????????????????????????????????????????????????????????
biplot(res.pca,c(1,2))
abline(h = 0, v = 0)
plot(res.pca)
```

```{r include=TRUE}
#?????????????????????????????????????????????
lambda <- res.pca$sdev^2
lambda
#?????????
cumsum(lambda)
#means with first 3 variable we can have all the infromation
#cumsum????????????
barplot(cumsum(lambda)/sum(lambda))
```

```{r include=TRUE}
#?????????
X <- scale(X, center = TRUE, scale = FALSE)
#eigen(S<-var(X)) -> res.mypca U<-res.mypac$vector C<-X%*%U
n <- nrow(X)
S = 1/n*t(X)%*%X
var(X)*(n-1)/n -> S
#eigen??????????????????????????????
eigen(S)$values -> lambda
eigen(S)$vectors -> U
#??????
C<-X%*%U
#c(1,2)???PC1 PC2??????dimension
plot(C[,1:2], type = "n")
abline(h = 0, v = 0)
text(C[,1:2], row.names(X))
```

```{r include=TRUE}
#??????????????????
res.pca$rotation ~ U
res.pca$x ~ C
res.pca$sdev ~ sqrt(lambda)
```
#??????FactoMineR???
###Exercise2
```{r include=TRUE}
library(MASS)
data(crabs)
crabsquant<-crabs[,seq(4,8,1)]

```
#E2
###Exercise2
```{r include=TRUE}
library(MASS)
data(crabs)
crabsquant<-crabs[,seq(4,8,1)]
```

Q1
```{r include=TRUE}
library(FactoMineR)
X <- data.frame(crabsquant, Sp.Sex = interaction(crabs$sp, crabs$sex))
PCA(X, quali.sup = 6) -> res.pca#????????????????????????
```
Q2
```{r include=TRUE}

plot.PCA(res.pca,axes=c(2,3),col.ind = c("blue1","blue4","orange1","orange4")[sex.sp=crabs$sp: crabs$sex])
#sex.sp=crabs$sp: crabs$sex ?????????????????????????????? F:B M:B F:O M:O
```

```{r include=TRUE}
library(ggplot2)
prcomp(X[,1:5], scale. = TRUE) -> res
p<-ggplot(data = data.frame(res$x), aes(x=PC2, y=PC3)) +
  geom_point(colour=c("blue1","blue4","orange1","orange4")[sex.sp=crabs$sp: crabs$sex]) +
  geom_vline(xintercept = 0) + 
  geom_hline(yintercept = 0) +
  geom_density2d()
#ggsave(fillename = "pac.pdf", p)
p

```

```{r include=TRUE}
#?????????????????????????????????????????????
plot(res)
```

