---
title: "Test"
author: "LI _Ziheng"
date: "2019/3/5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lubridate)
library(randomForest)
library(data.table)
library(mltools)
```


```{r, include=TRUE}
train <- read.csv(file = 'train.csv', header = TRUE)
store <- read.csv(file = 'store.csv', header = TRUE)
```


```{r, include=TRUE}

#left join
data <- left_join(train, store, by = c("Store" = "Store"))
# remove the attributes: "Customers", "open"
data
DataSet <- data[,-c(5, 6)]

```

```{r}
#先注释
year<-year(DataSet$Date)
week<-week(DataSet$Date)
month<-month(DataSet$Date)
```

```{r}
#remove the colomn Date, and add year, month, week.
DataSet
DataSet<-cbind(DataSet[,1:2],year,month,week,DataSet[,4:ncol(DataSet)])
```

```{r}
#is.na( DataSet$CompetitionOpenSinceMonth)&is.na( DataSet$CompetitionOpenSinceYear)&is.na( DataSet$CompetitionDistance)


#For any store which doesn’t has competitor (competitor==1), we assign CompetitionDistance as a large number 100000. 
DataSet$CompetitionDistance[is.na( DataSet$CompetitionOpenSinceMonth)&is.na( DataSet$CompetitionOpenSinceYear)&is.na( DataSet$CompetitionDistance)] <- 100000

#Impute miss value for CompetitionOpenSinceMonth and CompetitionOpenSinceYear by "na.roughfix"
DataSet$CompetitionOpenSinceMonth<-na.roughfix(DataSet$CompetitionOpenSinceMonth)
DataSet$CompetitionOpenSinceYear<-na.roughfix(DataSet$CompetitionOpenSinceYear)

condition1<-year<DataSet$CompetitionOpenSinceYear
condition2<-month<DataSet$CompetitionOpenSinceMonth
DataSet$CompetitionDistance[condition1&condition2] <- 100000


#remove  CompetitionOpenSinceMonth and CompetitionOpenSinceYear
DataSet <- DataSet[,-c(13,14)]

```

```{r}
#(DataSet$Promo2==1)&is.na(DataSet$Promo2SinceWeek)&is.na(DataSet$Promo2SinceYear)
#(DataSet$Promo2==1)&is.na(DataSet$PromoInterval)

#Combine Promo2, Promo2SinceWeek, Promo2SinceYear and Promointerval to a promotion 2 indicator in historical sales data. The indicator indicates on a certain day whether a certain store is on promotion 2.

condition3<-year<DataSet$Promo2SinceYear
condition4<-week<DataSet$Promo2SinceWeek
condition5<-DataSet$Promo2==1
#将日期在promo2开始之前的设为0
#for test sum( DataSet$Promo2[condition3&condition4&condition5])=190000
DataSet$Promo2[condition3&condition4&condition5]<-0
#for test sum( DataSet$Promo2[condition3&condition4&condition5])=0

```


```{r}
#promoInterval 
in_1_4_7_10<-DataSet$PromoInterval=='Jan,Apr,Jul,Oct'
in_2_5_8_11<-DataSet$PromoInterval=='Feb,May,Aug,Nov'
in_3_6_9_12<-DataSet$PromoInterval=='Mar,Jun,Sept,Dec'
#promo2 is 1, and month in PromoInterval
DataSet$Promo2[condition5&!(DataSet$month %in% c(1,4,7,10))&in_1_4_7_10]<-0
DataSet$Promo2[condition5&!(DataSet$month %in% c(2,5,8,11))&in_2_5_8_11]<-0
DataSet$Promo2[condition5&!(DataSet$month %in% c(3,6,9,12))&in_3_6_9_12]<-0


#remove Store, week, Promo2Sinceweek   Promo2Since year   PromoInterval
DataSet <- DataSet[,-c(1,5,14,15,16)]

DataSet<-DataSet[DataSet$Sales>0,]
DataSet <- na.omit(DataSet)
```

#Feature Selection

```{r, include=TRUE}
#boxplot(DataSet$Sales~DataSet$DayOfWeek, ylim = c(0,20000))
#We combine the Tuesday Wes, Thursday and Friday to one variable ,and we leave Monday and Saturday and Sunday 

DataSet[which(DataSet$DayOfWeek %in% c(3,4,5)),]$DayOfWeek = 2



#boxplot(DataSet$Sales~DataSet$DayOfWeek, ylim = c(0,20000))

#boxplot(DataSet$Sales~DataSet$month, ylim = c(0,10000))

DataSet[which(DataSet$month %in% c(1,2)),]$month = 1
DataSet[which(DataSet$month %in% c(3,4)),]$month = 3
DataSet[which(DataSet$month %in% c(5,6,7)),]$month = 5
DataSet[which(DataSet$month %in% c(8,9,10)),]$month = 8

#boxplot(DataSet$Sales~DataSet$month, ylim = c(0,10000))

DataSet$CompetitionDistance <- sqrt(DataSet$CompetitionDistance)

```

```{r, include=TRUE}
library(data.table)
library(mltools)
#We dont need to one hot cause it will decrease the performance of RandomF
#DataSet$DayOfWeek <- as.factor(DataSet$DayOfWeek)
#DataSet$year <- as.factor(DataSet$year)
##DataSet$month <- as.factor(DataSet$month)
#DataSet <- one_hot(as.data.table(DataSet))
```


#linear model
```{r, include=TRUE}
n <- dim(DataSet)[1]
TrainSize <- round(n)
TrainIndex <- sample(1:n, size = TrainSize)

NewDataset<- DataSet[TrainIndex,]

n <- dim(NewDataset)[1]
NewTrainSize <- round(n*.75)
NewTrainIndex <- sample(1:n, size = NewTrainSize)
NewTrain <-  NewDataset[NewTrainIndex,]
NewTest <-  NewDataset[-NewTrainIndex,]

```

```{r, include=TRUE}
modTrain = lm(Sales~., data = NewTrain)
summary(modTrain)
```


```{r}
library(MLmetrics)
pre = predict.lm(modTrain, newdata = NewTest[,-20])
cat("RMPSE =", RMSPE(pre,NewTest$Sales))

```  



```{r, include=TRUE}
library(MASS)
 modridge<-lm.ridge(Sales~.,data=TrainSet,lambda=seq(0,10,0.01))
lambda<-modridge$lambda[which.min(modridge$GCV)]
modridge<-lm.ridge(Sales~.,data=TrainSet,lambda=lambda)
coef<-coef(modridge)
un<-matrix(1,nrow=dim(as.vector(TestSet))[1],ncol=1)
Y_esti<-cbind(un,as.matrix(TestSet[,-8]))%*%as.vector(coef)
```



```{r, include=TRUE}
cat("RMSE =", sqrt(mean((Y_esti-TestSet$Sales)^2)))



plot(as.matrix(Y_esti[c(seq(1,100))])-TestSet$Sales[c(seq(1,100))],xlab = "index ",ylab="bias error",ylim=c(-10000,10000) )
abline(h=0)
abline(h=4000)
abline(h=-4000)
```


```{r, include=TRUE}

library(randomForest)
n <- dim(DataSet)[1]
TrainSize <- round(n*0.02)
TrainIndex <- sample(1:n, size = TrainSize)

NewDataset<- DataSet[TrainIndex,]

n <- dim(NewDataset)[1]

#修改100%数据
NewTrainSize <- round(n*.75)
NewTrainIndex <- sample(1:n, size = NewTrainSize)
NewTrain <-  NewDataset[NewTrainIndex,]
NewTest <-  NewDataset[-NewTrainIndex,]



```

```{r, include=TRUE}
NewTrain
```


```{r, include=TRUE}
library(MLmetrics)

RF33 <- randomForest(Sales~., data=NewTrain, ntree=100,mtry=20,replace=FALSE,nodesize=1)


pred<-predict(RF33,NewTest)
cat("RMSPE =",RMSPE(pred,NewTest$Sales),"\n")



```

```{r, include=TRUE}
library(MLmetrics)

for(i in 20:20)
{
  RF33_Test <- randomForest(Sales~., data=NewTrain_Test, ntree=150,mtry=i,replace=FALSE,nodesize=1)
  pred<-predict(RF33_Test,NewTest_Test)
  cat("i=",i,"RMSPE =",RMSPE(pred,NewTest_Test$Sales),"\n")
}


```



###test data
```{r}
test <- read.csv(file = 'test.csv', header = TRUE)
data_test <- left_join(test, store, by = c("Store" = "Store"))

#delete Id and Open
DataSet_test <- data_test[,-c(1,2,5)]
DataSet_test
```

```{r}
#先注释
year_Test<-year(DataSet_test$Date)
week_Test<-week(DataSet_test$Date)
month_Test<-month(DataSet_test$Date)

```

```{r}
#remove the colomn Date, and we add year, month, week
DayOfWeek <- DataSet_test[,1]

DataSet_test<-cbind(DayOfWeek,year_Test,month_Test,week_Test,DataSet_test[,3:ncol(DataSet_test)])
DataSet_test
```

```{r}
#is.na( DataSet$CompetitionOpenSinceMonth)&is.na( DataSet$CompetitionOpenSinceYear)&is.na( DataSet$CompetitionDistance)

#For any store which doesn’t has competitor (competitor==1), we assign CompetitionDistance as a large number 100000. 
DataSet_test$CompetitionDistance[is.na(DataSet_test$CompetitionOpenSinceMonth)&is.na(DataSet_test$CompetitionOpenSinceYear)&is.na( DataSet_test$CompetitionDistance)] <- 100000

#Impute miss value for CompetitionOpenSinceMonth and CompetitionOpenSinceYear by "na.roughfix"
DataSet_test$CompetitionOpenSinceMonth<-na.roughfix(DataSet_test$CompetitionOpenSinceMonth)
DataSet_test$CompetitionOpenSinceYear<-na.roughfix(DataSet_test$CompetitionOpenSinceYear)

condition1<-year_Test<DataSet_test$CompetitionOpenSinceYear
condition2<-month_Test<DataSet_test$CompetitionOpenSinceMonth
DataSet_test$CompetitionDistance[condition1&condition2] <- 100000


#remove  CompetitionOpenSinceMonth and CompetitionOpenSinceYear

DataSet_test <- DataSet_test[,-c(11,12)]

```

```{r}
#(DataSet$Promo2==1)&is.na(DataSet$Promo2SinceWeek)&is.na(DataSet$Promo2SinceYear)
#(DataSet$Promo2==1)&is.na(DataSet$PromoInterval)

#Combine Promo2, Promo2SinceWeek, Promo2SinceYear and Promointerval to a promotion 2 indicator in historical sales data. The indicator indicates on a certain day whether a certain store is on promotion 2.
DataSet_test
condition3<-year_Test<DataSet_test$Promo2SinceYear
condition4<-week_Test<DataSet_test$Promo2SinceWeek
condition5<-DataSet_test$Promo2==1
#将日期在promo2开始之前的设为0
#for test sum( DataSet$Promo2[condition3&condition4&condition5])=190000
DataSet_test$Promo2[condition3&condition4&condition5]<-0
#for test sum( DataSet$Promo2[condition3&condition4&condition5])=0

```


```{r}
#promoInterval 
in_1_4_7_10<-DataSet_test$PromoInterval=='Jan,Apr,Jul,Oct'
in_2_5_8_11<-DataSet_test$PromoInterval=='Feb,May,Aug,Nov'
in_3_6_9_12<-DataSet_test$PromoInterval=='Mar,Jun,Sept,Dec'
#promo2 is 1, and month in PromoInterval
DataSet_test$Promo2[condition5&!(DataSet_test$month_Test %in% c(1,4,7,10))&in_1_4_7_10]<-0
DataSet_test$Promo2[condition5&!(DataSet_test$month_Test %in% c(2,5,8,11))&in_2_5_8_11]<-0
DataSet_test$Promo2[condition5&!(DataSet_test$month_Test %in% c(3,6,9,12))&in_3_6_9_12]<-0


#remove  week, Promo2Sinceweek   Promo2Since year   PromoInterval

DataSet_test <- DataSet_test[,-c(4,12,13,14)]

DataSet_test <- na.omit(DataSet_test)
DataSet_test
```

#Feature Selection

```{r, include=TRUE}
#boxplot(DataSet$Sales~DataSet$DayOfWeek, ylim = c(0,20000))
#We combine the Tuesday Wes, Thursday and Friday to one variable ,and we leave Monday and Saturday and Sunday 

DataSet_test[which(DataSet_test$DayOfWeek %in% c(3,4,5)),]$DayOfWeek = 2



#boxplot(DataSet$Sales~DataSet$DayOfWeek, ylim = c(0,20000))

#boxplot(DataSet$Sales~DataSet$month, ylim = c(0,10000))

DataSet_test[which(DataSet_test$month_Test %in% c(8,9)),]$month_Test = 8.0

#boxplot(DataSet$Sales~DataSet$month, ylim = c(0,10000))

DataSet_test$CompetitionDistance <- sqrt(DataSet_test$CompetitionDistance)


```


```{r, include=TRUE}
names(DataSet_test)[2] <- "year"
names(DataSet_test)[3] <- "month"
DataSet_test_Test = DataSet_test
DataSet_test_Test = rbind(DataSet_test,NewTest[,-4])
DataSet_test_Test
```


```{r, include=TRUE}

pred<-predict(RF33,DataSet_test)
pred[which(data_test$Open!=1)] <- 0
pred<-na.roughfix(pred)
pred<-as.data.frame(cbind(seq(1,length(pred),1),pred))
names(pred) <- c("Id","Sales")
write.csv(pred,file = "res.csv")

```

```{r, include=TRUE}
DataSet
DataSet_test
types <- c()
for(i in 1:ncol(DataSet)){
  types [i] <- typeof(DataSet[1,i])
  } 
types

types1 <- c()
for(i in 1:ncol(DataSet_test)){
  types1[i] <- typeof(DataSet_test[1,i])
}
types1

```